dist: focal

jdk:
- openjdk11

before_install:
- echo $GPG_PASSWORD | gpg --batch --passphrase-fd 0 -o releng/enilink.asc --decrypt releng/enilink.asc.gpg
- gpg --import releng/enilink.asc

script: if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ] || [ "$TRAVIS_BRANCH" = "snapshots" ]; then mvn deploy -P ossrh,updatesite -s ./.travis.maven-settings.xml; else mvn verify; fi

deploy:
- provider: script
  skip_cleanup: true
  script: releng/publish/pushToBintray.sh features/net.enilink.komma.updatesite/target/repository/
  on:
    tags: true
    condition: false
- provider: script
  skip_cleanup: true
  script: releng/publish/pushToBintray.sh features/net.enilink.komma.updatesite/target/repository/ "$BINTRAY_USER" "$BINTRAY_API_KEY" "$BINTRAY_OWNER" snapshots
  on:
    branch: snapshots
    condition: false

env:
  global:
  - BINTRAY_USER: kenwenzel
  - BINTRAY_OWNER: komma
  - BINTRAY_REPO: updates
  - BINTRAY_PCK_NAME: komma
# GPG_PASSWORD
  - secure: Y992SWromNWz4gubDHKCZxCeL5434AV2gzQozoy2/ZUCK8Gt8+EwIrBb/v3khC5j83ejFa9+BxgXPSED5iHzz1gk6tCQvuUAkfcnaa7K5bIDIrJ8sH1PZW0QZ3BPOn8YVXiRSP0yisbUtgXJXce6MSEEZgDZaNj07zl/RiAjgMrhWQAYTQ+KPiD/ocvoypkwjERxKbzjQ8m+QiTB2R2jXjBP3miqhA0aj1RpTXGb38MmwWzY0bcrSLS2AHkxC++H+Q04u6AYsqyI/jzEmlQIxs++EJyTK21jEKvnQxTakDRWNhgky57WpZnLEDn/RN6r5CSCJIvEwrKCEX7NTUG9yVS5w4K7XEaY0p2ueK3qAi1mrcoAmTvtC57SlclAe+n1ueO2uoUuwzaUcp9F6hIE3WVxj6Dacia7jU2dS5HG5RBrFuQPEKVkwPKOyi5PfzuHnYwCP2bDiHfLe3j+h5QykYshM/PtzzSxvrl3/SPhHwl4xIXPiqCpNyAF0iCcB5L3y0rJYUjKq0MtokzPCRJdxpdcMiTOFi2N83aGaheyFB5Wg4h4nMLnzXZeTIzUp+Fx5bLayUPQmfnO1InaFqtpbTiy3CJtqi3yVkD+197O7M6rn/7dZ+Yhe5GM3lCmqfvNNW+QbVSXs2xnUAaU24p6OWC1+PleHI+kxYI9WWz8qsk=
# SONATYPE_USER
  - secure: BQyW8OEZUSURou8rOJC2E44uqZBCfo4j2Kje2MPvjvuJlwOMv3XoEy6qpdiB1cVRsuPFnsa1BMlWl4ZsqDqmA5dc8Y2vNvTP6vizcutAb9QCpMPZyHWsS0AcQWrdkDIrQlS+ReQ2GkA4RIBfPuFgD+zSNfBBhI3tQpYDdr92rGkGp6yWhl4GUJSoeTOcqYgLg4lT9ssYGrHE+y9UecD6a/xKK0HeRR34sbMXVvbnocyfJ0M5+sa8NSRfZQJLII0z1BkevI5PHO9hiLT6oTz5Oh7jnx4Xt+nIf6Y45lpfLoExBEhoP4fdEBVHDAxPMZA4JIg+EbIhdMknzga11+8o72aBtWY1NghYPNW742Ozv4GbdAbZ45EdzYr/91DlCWCu04aX0SfRzT9bA2TmpkIlcAVc93kyJ+5rbSC+S/64JV02+gr5kjnHpkzI1GapPzcQm84XW32nJvAEcjo2vlptKfUBueM6dMzVhQkVYbjAymdoFe7O8XoNFCD9wixD1y4g1VjXOvrceSik/ZIfcmQvimY2T5SLiQiMmyFiBaK39idLb8LVkD3vQua0g0wM/gvPyr4/xs9KbjszsOM6Da5mbFYwyLqasNrOmfCfQXhNHVIrAnJUC+hvA6E8W8s1sDAgIltsiK3ZbXHsxCvVNkRVbl/3iAWju6PxFRWTdTcqFmE=
# SONATYPE_PASSWORD
  - secure: R0QTdYAT8XM3NuqKZLA9EQkbfwolD0EbRUxZK/waBlcdtW2rIDURsxTGPUsqBHeKLMnrYAeVhvio0hBoiUqwPOMqoV2G+Xl2OQ/7+IoDHCQ+8f1/bL8coa+YBhNdZXZkMo0zo+ymVzffXegilXsojUhnDWMLhYIvst9BhyICen5XdcPrC0RyO0Sbsj5SXWXor1MX61DzhlCt5Rzs3HNdn6P48qk33mTaGApvARSvrD5m/Twn8AB84E2T8klms16jaJgFbXUWfjV9J8D3KmsTUzvVQTOn6XdkfZXUZijk2JDpb202Y+d4iyncDMN2KZ2Lmz2Trlfv3mnAYa5ttDIe7H32j9AyzElIMWlj64rToQ0BxOQGn32aswidtM7RTaDTC0lqQBoUjTE3l9uhYOAIOUg0wJylOaRsjR9xHtXSITEHjQUMaiqJyC3cpN6hA7OYYVutgtskRknI+49AuSWvDM4oQq/WxKDOPbqTvCad1oU/pRRDh8kpiRXvs/HLVTu9X9Y/lNoXGiADyoMxFCN9orRQQcYAqit6ueQJi4R8L/v5wWy143OT8chQBqLU42lmMkBj5LjanjgJD/nuU5lnkCUznoAoStNDy0WAr6rBv6Lo1ZT0jAtuD2QZW8hGT1mtjnJ447ddzB1G8t1p1rryMZRrVyqM5aVQJY/kV4Y1eWI=
