= KOMMA

KOMMA is a framework for linked data applications.

KOMMA (Knowledge Modeling and Management Architecture) supports the management and editing of RDF, RDFS and OWL. 
It provides Object-Triple-Mapping (comparable to JPA), an Editing framework as well as
Eclipse RCP and RAP integration. 

*In short:* KOMMA is for RDF+OWL what the Eclipse Modeling Framework (EMF) is for ECore/MOF.

* *Website:* http://komma.enilink.net
* *Documentation:* http://komma.enilink.net/docs
* *Eclipse Marketplace:* http://marketplace.eclipse.org/content/komma-rdf-eclipse
* *Eclipse Update Site:* http://dl.bintray.com/komma/updates/komma/1.3.2/

== Get the sources

[source,text]
----
git clone https://github.com/komma/komma
----

== Build KOMMA with Maven

KOMMA is a plain Maven project. You can simply use `mvn package` to compile and package all modules or `mvn install` to install them within your local Maven repository.

If you like to build an Eclipse update site (or rather a P2 repository) for KOMMA then use

[source,text]
----
cd features/net.enilink.komma.updatesite
mvn package
----

to create it. Afterwards a P2 repository can be found at `features/net.enilink.komma.updatesite/target/repository`.

== Develop KOMMA with Eclipse
For working with the sources we suggest you to download a recent version of 
http://www.eclipse.org/downloads/[Eclipse]. You can import the KOMMA projects into your workspace by executing 
__File > Import > Maven > Existing Maven Projects__.
