/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.enilink.komma.rdfs.edit;

import java.util.Arrays;
import java.util.Collection;
import java.util.Set;

import net.enilink.vocab.rdf.RDF;
import net.enilink.vocab.rdfs.RDFS;
import net.enilink.komma.common.util.IResourceLocator;
import net.enilink.komma.concepts.IClass;
import net.enilink.komma.concepts.IProperty;
import net.enilink.komma.edit.provider.ReflectiveItemProviderAdapterFactory;
import net.enilink.komma.model.IObject;
import net.enilink.komma.core.URI;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers. The adapters generated by this factory convert EMF adapter
 * notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The
 * adapters also support Eclipse property sheets. Note that most of the adapters
 * are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * 
 * @generated
 */
public class RDFSItemProviderAdapterFactory extends
		ReflectiveItemProviderAdapterFactory {
	public RDFSItemProviderAdapterFactory() {
		super(RDFSEditPlugin.INSTANCE, RDFS.NAMESPACE_URI, RDF.NAMESPACE_URI);
	}

	protected RDFSItemProviderAdapterFactory(IResourceLocator resourceLocator,
			URI... namespaceURIs) {
		super(resourceLocator, namespaceURIs);
	}

	@Override
	protected Collection<IClass> getTypes(Object object) {
		// classes
		if (object instanceof IClass) {
			return Arrays.asList((IClass) ((IObject) object).getModel()
					.getManager().find(RDFS.TYPE_CLASS));
		}
		if (object instanceof IProperty) {
			return Arrays.asList((IClass) ((IObject) object).getModel()
					.getManager().find(RDF.TYPE_PROPERTY));
		}
		// others
		Set<IClass> classes = ((IObject) object).getDirectNamedClasses()
				.toSet();
		return classes;
	}

	@Override
	protected Object createItemProvider(Object object,
			Collection<IClass> types, Object providerType) {
		if (object instanceof IClass) {
			return new RDFSClassItemProvider(this, resourceLocator, types);
		}
		return new RDFSPropertyItemProvider(this, resourceLocator, types);
	}
}
