name: Build and deploy to Sonatype

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - snapshots
    # Sequence of patterns matched against refs/tags
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Sets up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup key for signing
        - run: echo $GPG_PASSWORD | gpg --batch --passphrase-fd 0 -o releng/enilink.asc --decrypt releng/enilink.asc.gpg
        - run: gpg --import releng/enilink.asc

      # Runs the Maven build
      - name: Build and deploy with Maven
        run: mvn deploy -P ossrh,updatesite -s ./.ossrh.maven-settings.xml