name: Build and verify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-verify:
    # Configure the build matrix
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 17, 21 ]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4.1.1

      # Sets up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      # Runs the Maven build
      - name: Build and verify with Maven
        run: mvn verify
